/**
 * RTMP ingest server — mediamtx implementation.
 *
 * node-media-server v4 crashes with Node.js v20. Replaced with mediamtx
 * (already available in the Nix store), which is a battle-tested Go-based
 * media server that supports RTMP in + HLS out.
 *
 * Architecture:
 *   DJI Fly / OBS ──RTMP──▶ mediamtx :1935
 *                            └─ runOnPublish: FFmpeg → HLS files in /tmp/hls/live/
 *
 * mediamtx also exposes a REST API on :9997 so we can query active streams.
 *
 * mediamtx auto-download:
 *   If MEDIAMTX_BIN does not exist, the server downloads v1.12.2 from GitHub
 *   before starting. The binary is cached at the path specified by MEDIAMTX_BIN
 *   so subsequent restarts skip the download.
 */
import { spawn, execSync, type ChildProcess } from "child_process";
import path from "path";
import fs from "fs";
import { logger } from "./logger";

export const HLS_ROOT = "/tmp/hls";

/** HLS playlist path for a given mediamtx stream path (e.g. "live/abc123") */
export function hlsPlaylistPath(streamPath: string): string {
  return `${HLS_ROOT}/${streamPath}/index.m3u8`;
}

const MEDIAMTX_BIN = process.env.MEDIAMTX_BIN || "mediamtx";
const MEDIAMTX_CFG = "/tmp/mediamtx.yml";
const MEDIAMTX_API  = "http://127.0.0.1:9997";

let mediamtxProcess: ChildProcess | null = null;

// ─── Public API ───────────────────────────────────────────────────────────────

/** Returns keys of currently-active RTMP streams (polled from mediamtx API). */
export async function getActiveStreams(): Promise<string[]> {
  try {
    const res = await fetch(`${MEDIAMTX_API}/v3/paths/list`);
    if (!res.ok) return [];
    const data = (await res.json()) as { items: { name: string; ready: boolean }[] };
    return data.items.filter((p) => p.ready).map((p) => p.name);
  } catch {
    return [];
  }
}

/** Returns true if the HLS playlist file for the given mediamtx path exists on disk. */
export function isStreamActive(streamPath: string): boolean {
  return fs.existsSync(hlsPlaylistPath(streamPath));
}

/** Entry point called from index.ts */
export function createRtmpServer(rtmpPort = 1935): void {
  fs.mkdirSync(HLS_ROOT, { recursive: true });
  fs.mkdirSync(path.join(HLS_ROOT, "live"), { recursive: true });

  ensureMediamtxBinary();
  writeMediamtxConfig(rtmpPort);
  spawnMediamtx();

  logger.info({ rtmpPort }, "RTMP ingest server started (mediamtx)");
}

/**
 * Downloads mediamtx v1.12.2 if the binary at MEDIAMTX_BIN doesn't exist.
 * This makes the server self-contained after a fresh clone or container recycle.
 */
function ensureMediamtxBinary(): void {
  if (MEDIAMTX_BIN === "mediamtx") {
    // Using system PATH — assume it's installed externally.
    return;
  }
  if (fs.existsSync(MEDIAMTX_BIN)) {
    return;
  }
  logger.info({ path: MEDIAMTX_BIN }, "mediamtx binary not found — downloading…");
  try {
    const dir = path.dirname(MEDIAMTX_BIN);
    fs.mkdirSync(dir, { recursive: true });
    const tarball = "/tmp/mediamtx-setup.tar.gz";
    execSync(
      `wget -q https://github.com/bluenviron/mediamtx/releases/download/v1.12.2/mediamtx_v1.12.2_linux_amd64.tar.gz -O ${tarball}`,
      { stdio: "inherit" },
    );
    execSync(`tar -xzf ${tarball} -C ${dir} mediamtx`, { stdio: "inherit" });
    execSync(`chmod +x ${MEDIAMTX_BIN}`, { stdio: "inherit" });
    logger.info({ path: MEDIAMTX_BIN }, "mediamtx binary downloaded successfully");
  } catch (err) {
    logger.error({ err }, "Failed to download mediamtx — RTMP ingest will be unavailable");
  }
}

// ─── mediamtx lifecycle ───────────────────────────────────────────────────────

function writeMediamtxConfig(rtmpPort: number): void {
  // FFmpeg command mediamtx runs when a publisher connects.
  // $MTX_PATH is substituted by mediamtx with the stream path (e.g. "live/abc123").
  // We use "sh -c" so we can mkdir -p the per-stream output directory first.
  // Note: ${rtmpPort} is Node.js interpolation; $MTX_PATH is a mediamtx shell variable.
  const onPublishCmd =
    `sh -c 'mkdir -p ${HLS_ROOT}/$MTX_PATH && ` +
    `ffmpeg -y -i rtmp://127.0.0.1:${rtmpPort}/$MTX_PATH ` +
    `-c:v copy -c:a aac -ar 44100 -ac 2 ` +
    `-f hls -hls_time 1 -hls_list_size 5 ` +
    `-hls_flags delete_segments+append_list -hls_allow_cache 0 ` +
    `${HLS_ROOT}/$MTX_PATH/index.m3u8'`;

  const cfg = `
# mediamtx configuration — generated by OBS Web api-server

logLevel: info
logDestinations: [stdout]

# API (used to query active streams)
api: yes
apiAddress: 127.0.0.1:9997

# RTMP only — everything else disabled
rtsp: no
hls: no
webrtc: no
srt: no

rtmp: yes
rtmpAddress: :${rtmpPort}
rtmpEncryption: "no"

paths:
  "~.*":
    runOnReady: ${onPublishCmd}
    runOnReadyRestart: yes
`;

  fs.writeFileSync(MEDIAMTX_CFG, cfg, "utf-8");
  logger.info({ cfg: MEDIAMTX_CFG }, "mediamtx config written");
}

function spawnMediamtx(): void {
  if (mediamtxProcess) {
    mediamtxProcess.kill();
    mediamtxProcess = null;
  }

  const proc = spawn(MEDIAMTX_BIN, [MEDIAMTX_CFG], {
    stdio: ["ignore", "pipe", "pipe"],
  });

  mediamtxProcess = proc;

  const onData = (d: Buffer) => {
    const line = d.toString().trim();
    if (line) logger.debug({ mediamtx: line }, "mediamtx");
  };
  proc.stdout?.on("data", onData);
  proc.stderr?.on("data", onData);

  proc.on("close", (code) => {
    logger.warn({ code }, "mediamtx exited — restarting in 3 s");
    mediamtxProcess = null;
    setTimeout(spawnMediamtx, 3000);
  });

  proc.on("error", (err) => {
    logger.error({ err }, "mediamtx spawn error");
    mediamtxProcess = null;
    setTimeout(spawnMediamtx, 5000);
  });

  logger.info("mediamtx started");
}
