/**
 * RTMP ingest server — mediamtx implementation.
 *
 * node-media-server v4 crashes with Node.js v20. Replaced with mediamtx
 * (already available in the Nix store), which is a battle-tested Go-based
 * media server that supports RTMP in + HLS out.
 *
 * Architecture:
 *   DJI Fly / OBS ──RTMP──▶ mediamtx :1935
 *                            └─ runOnPublish: FFmpeg → HLS files in /tmp/hls/live/
 *
 * mediamtx also exposes a REST API on :9997 so we can query active streams.
 */
import { spawn, type ChildProcess } from "child_process";
import path from "path";
import fs from "fs";
import { logger } from "./logger";

export const HLS_ROOT = "/tmp/hls";

/** HLS playlist path for a given mediamtx stream path (e.g. "live/abc123") */
export function hlsPlaylistPath(streamPath: string): string {
  return `${HLS_ROOT}/${streamPath}/index.m3u8`;
}

const MEDIAMTX_BIN =
  "/nix/store/692k40917r79aryiym4rdgpjnm3vn7fd-mediamtx-1.12.2/bin/mediamtx";
const MEDIAMTX_CFG = "/tmp/mediamtx.yml";
const MEDIAMTX_API  = "http://127.0.0.1:9997";

let mediamtxProcess: ChildProcess | null = null;

// ─── Public API ───────────────────────────────────────────────────────────────

/** Returns keys of currently-active RTMP streams (polled from mediamtx API). */
export async function getActiveStreams(): Promise<string[]> {
  try {
    const res = await fetch(`${MEDIAMTX_API}/v3/paths/list`);
    if (!res.ok) return [];
    const data = (await res.json()) as { items: { name: string; ready: boolean }[] };
    return data.items.filter((p) => p.ready).map((p) => p.name);
  } catch {
    return [];
  }
}

/** Returns true if the HLS playlist file for the given mediamtx path exists on disk. */
export function isStreamActive(streamPath: string): boolean {
  return fs.existsSync(hlsPlaylistPath(streamPath));
}

/** Entry point called from index.ts */
export function createRtmpServer(rtmpPort = 1935): void {
  fs.mkdirSync(HLS_ROOT, { recursive: true });
  fs.mkdirSync(path.join(HLS_ROOT, "live"), { recursive: true });

  writeMediamtxConfig(rtmpPort);
  spawnMediamtx();

  logger.info({ rtmpPort }, "RTMP ingest server started (mediamtx)");
}

// ─── mediamtx lifecycle ───────────────────────────────────────────────────────

function writeMediamtxConfig(rtmpPort: number): void {
  // FFmpeg command mediamtx runs when a publisher connects.
  // $MTX_PATH is substituted by mediamtx with the stream path (e.g. "live/abc123").
  // We use "sh -c" so we can mkdir -p the per-stream output directory first.
  // Note: ${rtmpPort} is Node.js interpolation; $MTX_PATH is a mediamtx shell variable.
  const onPublishCmd =
    `sh -c 'mkdir -p ${HLS_ROOT}/$MTX_PATH && ` +
    `ffmpeg -y -i rtmp://127.0.0.1:${rtmpPort}/$MTX_PATH ` +
    `-c:v copy -c:a aac -ar 44100 -ac 2 ` +
    `-f hls -hls_time 1 -hls_list_size 5 ` +
    `-hls_flags delete_segments+append_list -hls_allow_cache 0 ` +
    `${HLS_ROOT}/$MTX_PATH/index.m3u8'`;

  const cfg = `
# mediamtx configuration — generated by OBS Web api-server

logLevel: info
logDestinations: [stdout]

# API (used to query active streams)
api: yes
apiAddress: 127.0.0.1:9997

# RTMP only — everything else disabled
rtsp: no
hls: no
webrtc: no
srt: no

rtmp: yes
rtmpAddress: :${rtmpPort}
rtmpEncryption: "no"

paths:
  "~.*":
    runOnReady: ${onPublishCmd}
    runOnReadyRestart: yes
`;

  fs.writeFileSync(MEDIAMTX_CFG, cfg, "utf-8");
  logger.info({ cfg: MEDIAMTX_CFG }, "mediamtx config written");
}

function spawnMediamtx(): void {
  if (mediamtxProcess) {
    mediamtxProcess.kill();
    mediamtxProcess = null;
  }

  const proc = spawn(MEDIAMTX_BIN, [MEDIAMTX_CFG], {
    stdio: ["ignore", "pipe", "pipe"],
  });

  mediamtxProcess = proc;

  const onData = (d: Buffer) => {
    const line = d.toString().trim();
    if (line) logger.debug({ mediamtx: line }, "mediamtx");
  };
  proc.stdout?.on("data", onData);
  proc.stderr?.on("data", onData);

  proc.on("close", (code) => {
    logger.warn({ code }, "mediamtx exited — restarting in 3 s");
    mediamtxProcess = null;
    setTimeout(spawnMediamtx, 3000);
  });

  proc.on("error", (err) => {
    logger.error({ err }, "mediamtx spawn error");
    mediamtxProcess = null;
    setTimeout(spawnMediamtx, 5000);
  });

  logger.info("mediamtx started");
}
